program: #TODO: make this a list with ids
  minutesPerUnit: 0
  picsPerLevel: 1
  gameSequence:
    - game: gTouchPic
      startLevel: 0
    - game: gTouchColors
      startLevel: 6
    - game: gTouchPic
      startLevel: 6
    # - game: gSayPic
    #   startLevel: 9
    - game: gWritePic
      startLevel: 9
  currentGameIndex: 0
  currentLevel: 8
common:
  # loopGameSequence: true
  currentUser: Gunter
  currentLanguage: E
  # activity animal body drink emotion food fruit game gesture kitchen 
  # object person place plant role sport time transport vegetable 
  # nosymemo nosymbols
  currentCategories: [nosymemo]
games: 
  gTouchColors:
    contrast: 0.32
    colors:
      - red
      - blue
      - yellow
      - green
      
#     levels: #changes to common for specific levels
#     - 0:
#         colors: [red, yellow]
      