settings:
  loopGameSequence: true
program: #TODO: make this a list with ids
  username: Gunter
  GameSequence:
    - g: gTouchColors
      sl: 8
    - g: gMissingLetter
      sl: 6
    - g: gTouchPic
      sl: 9
    - g: gWritePic
      sl: 9
games:
  common: #valid for all games (can be overwritten by indiv games!)
    language: E
    categories: [nosymbols]
    picsPerLevel: 5
  gTouchColors:
    common: #valid for all levels
      colors:
        - red
        - blue
        - yellow
        - green
        - black
    level: #changes to common for specific levels