program: #TODO: make this a list with ids
  minutesPerUnit: .25
  picsPerLevel: 1
  gameSequence:
    - game: gTouchPic
      startLevel: 0
    - game: gMissingLetter
      startLevel: 0
    - game: gTouchColors
      startLevel: 0
    - game: gWritePic
      startLevel: 0
    - game: gSayPic
      startLevel: 0
  currentGameIndex: 0
  currentLevel: 0
common:
  # loopGameSequence: true
  currentUser: Gunter
  currentLanguage: E
  # activity animal body drink emotion food fruit game gesture kitchen 
  # object person place plant role sport time transport vegetable 
  # nosymemo nosymbols
  currentCategories: [nosymemo]
flags:
  pressControlToUnfreeze: false
  reducedAnimations: true
games: 
  gTouchColors:
    contrast: 0.32
    colors:
      - red
      - blue
      - yellow
      - green
      
#     levels: #changes to common for specific levels
#     - 0:
#         colors: [red, yellow]
      